version: '3'

services: 

    mirror:
        build: .
        command: bash -c "apt-mirror && bash /apt-mirror/postmirror.sh"
        volumes:
            - "./mirror:/var/spool/apt-mirror"

    server:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - "./mirror/mirror:/mirror:ro"
        ports:
            - "8080:80"
